import fs from 'fs/promises';
import path from 'path';
import PptxGenJS from 'pptxgenjs';
import { WorkerInput, WorkerResult, GeneratedArtifact, IRBlockNode, IRInlineNode, flattenInline } from '../../shared/types';
import { sanitizeFilename } from '../../shared/utils';
import { walkIR, findNodesByType } from '../ir/traversal';
import { BaseWorker } from './base';

export class PPTXWorker extends BaseWorker {
  readonly id = 'pptx';
  readonly name = 'PPTX';
  readonly formats = ['pptx'];

  protected async process(input: WorkerInput): Promise<Omit<WorkerResult, 'duration'>> {
    const { ir, outputDir, sourceFile } = input;

    const pptx = new PptxGenJS();
    pptx.author = 'Papyrus';
    pptx.title = ir.title || 'Untitled';
    pptx.layout = 'LAYOUT_16x9';

    const slides = findNodesByType(ir, 'slide') as unknown as { type: 'slide'; title: string; children: IRBlockNode[] }[];

    if (slides.length > 0) {
      for (const slide of slides) {
        this.addSlide(pptx, slide.title, slide.children);
      }
    } else {
      this.addDocumentSlides(pptx, ir);
    }

    const pptxBuffer = await pptx.write({ outputType: 'nodebuffer' as const });
    const data = new Uint8Array(pptxBuffer as ArrayBuffer);

    const baseName = sourceFile
      ? path.basename(sourceFile, path.extname(sourceFile))
      : sanitizeFilename(ir.title || 'output');
    const filename = `${baseName}.pptx`;
    const outputPath = path.join(outputDir, filename);

    await fs.mkdir(outputDir, { recursive: true });
    await fs.writeFile(outputPath, data);

    this.logger.info(`Wrote ${data.byteLength} bytes to ${outputPath}`);

    return {
      success: true,
      artifacts: [this.makeArtifact(filename, data, 'pptx')],
      errors: [],
      warnings: [],
    };
  }

  private addSlide(pptx: PptxGenJS, title: string, children: IRBlockNode[]): void {
    const slide = pptx.addSlide();

    slide.addText(title, {
      x: 0.5,
      y: 0.2,
      w: 9,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: '2F5496',
    });

    let yPos = 1.2;
    for (const child of children) {
      const element = this.convertNode(child, 0.5, yPos);
      if (element) {
        slide.addText(element.text, element.options);
        yPos += element.height;
      }
    }
  }

  private addDocumentSlides(pptx: PptxGenJS, ir: any): void {
    const titleSlide = pptx.addSlide();
    titleSlide.addText(ir.title || 'Untitled', {
      x: 0.5,
      y: 2.0,
      w: 9,
      h: 1.5,
      fontSize: 36,
      bold: true,
      color: '2F5496',
      align: 'center',
    });
    titleSlide.addText('Generated by Papyrus', {
      x: 0.5,
      y: 3.8,
      w: 9,
      h: 0.5,
      fontSize: 14,
      color: '888888',
      align: 'center',
    });

    if (ir.children) {
      for (const child of ir.children) {
        this.addNodeSlide(pptx, child);
      }
    }
  }

  private addNodeSlide(pptx: PptxGenJS, node: IRBlockNode): void {
    switch (node.type) {
      case 'section':
        this.addSectionSlide(pptx, node as any);
        break;
      case 'table':
        this.addTableSlide(pptx, node as any);
        break;
      case 'paragraph':
        this.addParagraphSlide(pptx, node as any);
        break;
      case 'list':
        this.addListSlide(pptx, node as any);
        break;
      case 'code':
        this.addCodeSlide(pptx, node as any);
        break;
      case 'quote':
        this.addQuoteSlide(pptx, node as any);
        break;
      case 'image':
        this.addImageSlide(pptx, node as any);
        break;
      default:
        break;
    }
  }

  private addSectionSlide(pptx: PptxGenJS, node: { type: 'section'; level: number; title: string; children: IRBlockNode[] }): void {
    const slide = pptx.addSlide();
    slide.addText(node.title, {
      x: 0.5,
      y: 0.2,
      w: 9,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: '2F5496',
    });

    let yPos = 1.2;
    for (const child of node.children) {
      const element = this.convertNode(child, 0.5, yPos);
      if (element) {
        slide.addText(element.text, element.options);
        yPos += element.height;
      }
    }
  }

  private addTableSlide(pptx: PptxGenJS, node: { type: 'table'; headers: string[]; rows: string[][] }): void {
    const slide = pptx.addSlide();
    slide.addText('Table', {
      x: 0.5,
      y: 0.2,
      w: 9,
      h: 0.6,
      fontSize: 20,
      bold: true,
      color: '2F5496',
    });

    const tableRows = [node.headers.map(h => ({ text: h })), ...node.rows.map(row => row.map(cell => ({ text: cell })))];
    slide.addTable(tableRows, {
      x: 0.5,
      y: 1.0,
      w: 9,
      fontSize: 10,
      border: { type: 'solid', pt: 1, color: 'CCCCCC' },
      colW: node.headers.map(() => Math.floor(9 / node.headers.length)),
    });
  }

  private addParagraphSlide(pptx: PptxGenJS, node: { type: 'paragraph'; content: string }): void {
    const slide = pptx.addSlide();
    slide.addText(node.content, {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 4,
      fontSize: 14,
      valign: 'top',
    });
  }

  private addListSlide(pptx: PptxGenJS, node: { type: 'list'; ordered: boolean; items: { content: string }[] }): void {
    const slide = pptx.addSlide();
    const bulletChar = node.ordered ? '' : '\u2022 ';

    const listText = node.items
      .map((item, index) => {
        const prefix = node.ordered ? `${index + 1}. ` : bulletChar;
        return { text: `${prefix}${item.content}\n`, options: { fontSize: 14, bullet: !node.ordered } };
      });

    slide.addText(listText, {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 4,
      valign: 'top',
    });
  }

  private addCodeSlide(pptx: PptxGenJS, node: { type: 'code'; language: string; content: string }): void {
    const slide = pptx.addSlide();

    if (node.language) {
      slide.addText(`Language: ${node.language}`, {
        x: 0.5,
        y: 0.2,
        w: 9,
        h: 0.4,
        fontSize: 10,
        italic: true,
        color: '666666',
      });
    }

    slide.addText(node.content, {
      x: 0.5,
      y: 0.7,
      w: 9,
      h: 4.5,
      fontSize: 10,
      fontFace: 'Courier New',
      fill: { color: 'F5F5F5' },
      valign: 'top',
    });
  }

  private addQuoteSlide(pptx: PptxGenJS, node: { type: 'quote'; content: string; author?: string }): void {
    const slide = pptx.addSlide();

    slide.addText(`"${node.content}"`, {
      x: 1.0,
      y: 1.5,
      w: 8,
      h: 2.5,
      fontSize: 18,
      italic: true,
      color: '333333',
      align: 'center',
    });

    if (node.author) {
      slide.addText(`— ${node.author}`, {
        x: 1.0,
        y: 4.0,
        w: 8,
        h: 0.5,
        fontSize: 12,
        bold: true,
        color: '2F5496',
        align: 'center',
      });
    }
  }

  private addImageSlide(pptx: PptxGenJS, node: { type: 'image'; src: string; alt?: string }): void {
    const slide = pptx.addSlide();

    slide.addText(`[Image: ${node.alt || node.src}]`, {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 4,
      fontSize: 14,
      italic: true,
      color: '888888',
      align: 'center',
      valign: 'middle',
    });
  }

  private convertNode(
    node: IRBlockNode,
    x: number,
    y: number
  ): { text: string; options: any; height: number } | null {
    switch (node.type) {
      case 'paragraph': {
        const pText = node.inline?.length ? flattenInline(node.inline) : node.content;
        return {
          text: pText,
          options: { x, y, w: 9, h: 0.5, fontSize: 14 },
          height: 0.6,
        };
      }
      case 'list': {
        const lText = node.items.map((item) => {
          const itemText = item.inline?.length ? flattenInline(item.inline) : item.content;
          return `\u2022 ${itemText}`;
        }).join('\n');
        return {
          text: lText,
          options: { x, y, w: 9, h: 1.0, fontSize: 12, valign: 'top' },
          height: 1.1,
        };
      }
      case 'code':
        return {
          text: node.content,
          options: { x, y, w: 9, h: 0.8, fontSize: 10, fontFace: 'Courier New', fill: { color: 'F5F5F5' } },
          height: 0.9,
        };
      case 'quote': {
        const qText = node.inline?.length ? flattenInline(node.inline) : node.content;
        const qAuthor = node.author ? ` — ${node.author}` : '';
        return {
          text: `"${qText}"${qAuthor}`,
          options: { x, y, w: 9, h: 0.6, fontSize: 12, italic: true, color: '555555' },
          height: 0.7,
        };
      }
      case 'table': {
        const tRows = node.rows?.map(r => r.join(' | ')).join('\n') || '';
        return {
          text: tRows ? `${node.headers.join(' | ')}\n${tRows}` : node.headers.join(' | '),
          options: { x, y, w: 9, h: 0.5, fontSize: 10 },
          height: 0.6,
        };
      }
      default:
        return null;
    }
  }
}
